ALTER TABLE courses
ADD CONSTRAINT courses_course_id_key UNIQUE (course_id);

ALTER TABLE grades
ALTER COLUMN earned TYPE DOUBLE PRECISION
USING earned::DOUBLE PRECISION;

ALTER TABLE grades
ALTER COLUMN total TYPE DOUBLE PRECISION
USING total::DOUBLE PRECISION;
