// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 01_grades.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGradeRows = `-- name: CountGradeRows :one
SELECT COUNT(*)
FROM grades g
JOIN courses c ON g.id_course = c.id
WHERE ($1::text = '' OR g.id_course::text = $1::text OR c.course_id = $1::text)
  AND ($2::text = '' OR g.assignment_name ILIKE '%' || $2::text || '%')
`

type CountGradeRowsParams struct {
	CourseID string
	Search   string
}

func (q *Queries) CountGradeRows(ctx context.Context, arg CountGradeRowsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGradeRows, arg.CourseID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGrade = `-- name: CreateGrade :one
INSERT INTO grades (
    id_course,
    category_id,
    assignment_name,
    earned,
    total,
    g_status,
    posted_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, id_course, category_id, assignment_name, earned, total, g_status, posted_date
`

type CreateGradeParams struct {
	IDCourse       pgtype.UUID
	CategoryID     pgtype.UUID
	AssignmentName string
	Earned         pgtype.Float8
	Total          pgtype.Float8
	GStatus        GradeStatus
	PostedDate     pgtype.Timestamptz
}

func (q *Queries) CreateGrade(ctx context.Context, arg CreateGradeParams) (Grade, error) {
	row := q.db.QueryRow(ctx, createGrade,
		arg.IDCourse,
		arg.CategoryID,
		arg.AssignmentName,
		arg.Earned,
		arg.Total,
		arg.GStatus,
		arg.PostedDate,
	)
	var i Grade
	err := row.Scan(
		&i.ID,
		&i.IDCourse,
		&i.CategoryID,
		&i.AssignmentName,
		&i.Earned,
		&i.Total,
		&i.GStatus,
		&i.PostedDate,
	)
	return i, err
}

const deleteGrade = `-- name: DeleteGrade :exec
DELETE FROM grades
WHERE id = $1
`

func (q *Queries) DeleteGrade(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGrade, id)
	return err
}

const deleteGradesByCourse = `-- name: DeleteGradesByCourse :exec
DELETE FROM grades
WHERE id_course = $1
`

func (q *Queries) DeleteGradesByCourse(ctx context.Context, idCourse pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGradesByCourse, idCourse)
	return err
}

const getGradeByID = `-- name: GetGradeByID :one
SELECT id, id_course, category_id, assignment_name, earned, total, g_status, posted_date
FROM grades
WHERE id = $1
`

func (q *Queries) GetGradeByID(ctx context.Context, id pgtype.UUID) (Grade, error) {
	row := q.db.QueryRow(ctx, getGradeByID, id)
	var i Grade
	err := row.Scan(
		&i.ID,
		&i.IDCourse,
		&i.CategoryID,
		&i.AssignmentName,
		&i.Earned,
		&i.Total,
		&i.GStatus,
		&i.PostedDate,
	)
	return i, err
}

const getGrades = `-- name: GetGrades :many
SELECT
    g.id,
    g.id_course,
    g.category_id,
    cat.category_name,
    g.assignment_name,
    g.earned,
    g.total,
    g.g_status,
    g.posted_date
FROM grades g
JOIN courses c ON g.id_course = c.id
LEFT JOIN category cat ON g.category_id = cat.id
WHERE ($1::text = '' OR g.id_course::text = $1::text OR c.course_id = $1::text)
  AND ($2::text = '' OR g.assignment_name ILIKE '%' || $2::text || '%')
ORDER BY
    -- Sort by grade value (Ratio calculation)
    CASE WHEN $3::text = 'grade' AND $4::text = 'asc' THEN (g.earned / NULLIF(g.total, 0)) END ASC NULLS FIRST,
    CASE WHEN $3::text = 'grade' AND $4::text = 'desc' THEN (g.earned / NULLIF(g.total, 0)) END DESC NULLS FIRST,
    -- Sort by date
    CASE WHEN $3::text = 'date' AND $4::text = 'asc' THEN g.posted_date END ASC,
    CASE WHEN $3::text = 'date' AND $4::text = 'desc' THEN g.posted_date END DESC,
    -- Sort by assignment name
    CASE WHEN $3::text = 'assignment' AND $4::text = 'asc' THEN LOWER(g.assignment_name) END ASC,
    CASE WHEN $3::text = 'assignment' AND $4::text = 'desc' THEN LOWER(g.assignment_name) END DESC,
    -- Default fallback
    g.posted_date DESC,
    g.id ASC
LIMIT $6::int
OFFSET $5::int
`

type GetGradesParams struct {
	CourseID   string
	Search     string
	SortBy     string
	SortDir    string
	PageOffset int32
	NumRows    int32
}

type GetGradesRow struct {
	ID             pgtype.UUID
	IDCourse       pgtype.UUID
	CategoryID     pgtype.UUID
	CategoryName   pgtype.Text
	AssignmentName string
	Earned         pgtype.Float8
	Total          pgtype.Float8
	GStatus        GradeStatus
	PostedDate     pgtype.Timestamptz
}

func (q *Queries) GetGrades(ctx context.Context, arg GetGradesParams) ([]GetGradesRow, error) {
	rows, err := q.db.Query(ctx, getGrades,
		arg.CourseID,
		arg.Search,
		arg.SortBy,
		arg.SortDir,
		arg.PageOffset,
		arg.NumRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGradesRow
	for rows.Next() {
		var i GetGradesRow
		if err := rows.Scan(
			&i.ID,
			&i.IDCourse,
			&i.CategoryID,
			&i.CategoryName,
			&i.AssignmentName,
			&i.Earned,
			&i.Total,
			&i.GStatus,
			&i.PostedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGradesForReconciliation = `-- name: GetGradesForReconciliation :many
SELECT
    id,
    id_course,
    assignment_name,
    category_id
FROM grades
WHERE id_course = $1
ORDER BY posted_date DESC, id ASC
`

type GetGradesForReconciliationRow struct {
	ID             pgtype.UUID
	IDCourse       pgtype.UUID
	AssignmentName string
	CategoryID     pgtype.UUID
}

func (q *Queries) GetGradesForReconciliation(ctx context.Context, idCourse pgtype.UUID) ([]GetGradesForReconciliationRow, error) {
	rows, err := q.db.Query(ctx, getGradesForReconciliation, idCourse)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGradesForReconciliationRow
	for rows.Next() {
		var i GetGradesForReconciliationRow
		if err := rows.Scan(
			&i.ID,
			&i.IDCourse,
			&i.AssignmentName,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGrade = `-- name: UpdateGrade :one
UPDATE grades
SET
    assignment_name = COALESCE($1, assignment_name),
    earned = COALESCE($2, earned),
    total = COALESCE($3, total),
    g_status = COALESCE($4, g_status),
    posted_date = COALESCE($5, posted_date),
    category_id = CASE
        WHEN $6::boolean THEN $7
        ELSE category_id
    END
WHERE id = $8
RETURNING id, id_course, category_id, assignment_name, earned, total, g_status, posted_date
`

type UpdateGradeParams struct {
	AssignmentName pgtype.Text
	Earned         pgtype.Float8
	Total          pgtype.Float8
	GStatus        NullGradeStatus
	PostedDate     pgtype.Timestamptz
	CategoryIDSet  bool
	CategoryID     pgtype.UUID
	ID             pgtype.UUID
}

func (q *Queries) UpdateGrade(ctx context.Context, arg UpdateGradeParams) (Grade, error) {
	row := q.db.QueryRow(ctx, updateGrade,
		arg.AssignmentName,
		arg.Earned,
		arg.Total,
		arg.GStatus,
		arg.PostedDate,
		arg.CategoryIDSet,
		arg.CategoryID,
		arg.ID,
	)
	var i Grade
	err := row.Scan(
		&i.ID,
		&i.IDCourse,
		&i.CategoryID,
		&i.AssignmentName,
		&i.Earned,
		&i.Total,
		&i.GStatus,
		&i.PostedDate,
	)
	return i, err
}

const updateGradeCategory = `-- name: UpdateGradeCategory :exec
UPDATE grades
SET category_id = $1
WHERE id = $2
`

type UpdateGradeCategoryParams struct {
	CategoryID pgtype.UUID
	ID         pgtype.UUID
}

func (q *Queries) UpdateGradeCategory(ctx context.Context, arg UpdateGradeCategoryParams) error {
	_, err := q.db.Exec(ctx, updateGradeCategory, arg.CategoryID, arg.ID)
	return err
}
