// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 02_categories.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO category (
    id_course,
    category_name,
    weight
) VALUES (
    $1, $2, $3
)
RETURNING id, id_course, category_name, weight
`

type CreateCategoryParams struct {
	IDCourse     pgtype.UUID
	CategoryName string
	Weight       float64
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.IDCourse, arg.CategoryName, arg.Weight)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.IDCourse,
		&i.CategoryName,
		&i.Weight,
	)
	return i, err
}

const deleteCategoriesByCourse = `-- name: DeleteCategoriesByCourse :exec
DELETE FROM category
WHERE id_course = $1
`

func (q *Queries) DeleteCategoriesByCourse(ctx context.Context, idCourse pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategoriesByCourse, idCourse)
	return err
}

const getCategoriesByCourse = `-- name: GetCategoriesByCourse :many
SELECT
    id,
    id_course,
    category_name,
    weight
FROM category
WHERE id_course = $1
ORDER BY category_name ASC
`

func (q *Queries) GetCategoriesByCourse(ctx context.Context, idCourse pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategoriesByCourse, idCourse)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.IDCourse,
			&i.CategoryName,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByCourseAndID = `-- name: GetCategoryByCourseAndID :one
SELECT
    id,
    id_course,
    category_name,
    weight
FROM category
WHERE id = $1
  AND id_course = $2
`

type GetCategoryByCourseAndIDParams struct {
	ID       pgtype.UUID
	IDCourse pgtype.UUID
}

func (q *Queries) GetCategoryByCourseAndID(ctx context.Context, arg GetCategoryByCourseAndIDParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByCourseAndID, arg.ID, arg.IDCourse)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.IDCourse,
		&i.CategoryName,
		&i.Weight,
	)
	return i, err
}
