// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type GradeStatus string

const (
	GradeStatusGRADEED   GradeStatus = "GRADEED"
	GradeStatusNOTGRADED GradeStatus = "NOT GRADED"
	GradeStatusNA        GradeStatus = "N/A"
)

func (e *GradeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GradeStatus(s)
	case string:
		*e = GradeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GradeStatus: %T", src)
	}
	return nil
}

type NullGradeStatus struct {
	GradeStatus GradeStatus
	Valid       bool // Valid is true if GradeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGradeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GradeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GradeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGradeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GradeStatus), nil
}

type Course struct {
	ID            pgtype.UUID
	CourseName    string
	CourseID      string
	ProfessorName string
}

type Grade struct {
	ID         pgtype.UUID
	IDCourse   pgtype.UUID
	Grade      int32
	GStatus    GradeStatus
	PostedDate pgtype.Timestamptz
}
