// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 01_courses.sql

package repository

import (
	"context"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (
    course_name,
    course_id,
    professor_name
) VALUES (
    $1, $2, $3
)
RETURNING id, course_name, course_id, professor_name
`

type CreateCourseParams struct {
	CourseName    string
	CourseID      string
	ProfessorName string
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse, arg.CourseName, arg.CourseID, arg.ProfessorName)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CourseName,
		&i.CourseID,
		&i.ProfessorName,
	)
	return i, err
}

const getCourses = `-- name: GetCourses :many
SELECT id, course_name, course_id, professor_name FROM courses
ORDER BY course_name ASC
`

func (q *Queries) GetCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.Query(ctx, getCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.CourseName,
			&i.CourseID,
			&i.ProfessorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
