// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 01_grades.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGradeRows = `-- name: CountGradeRows :one
SELECT COUNT(*)
FROM grades g
JOIN courses c ON g.id_course = c.id
WHERE $1 = '' 
   OR c.course_name ILIKE '%' || $1 || '%' 
   OR c.course_id ILIKE '%' || $1 || '%'
   OR c.professor_name ILIKE '%' || $1 || '%'
`

func (q *Queries) CountGradeRows(ctx context.Context, search interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countGradeRows, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGrade = `-- name: CreateGrade :one
INSERT INTO grades (
    id_course, 
    grade, 
    g_status, 
    posted_date
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, id_course, grade, g_status, posted_date
`

type CreateGradeParams struct {
	IDCourse   pgtype.UUID
	Grade      int32
	GStatus    GradeStatus
	PostedDate pgtype.Timestamptz
}

func (q *Queries) CreateGrade(ctx context.Context, arg CreateGradeParams) (Grade, error) {
	row := q.db.QueryRow(ctx, createGrade,
		arg.IDCourse,
		arg.Grade,
		arg.GStatus,
		arg.PostedDate,
	)
	var i Grade
	err := row.Scan(
		&i.ID,
		&i.IDCourse,
		&i.Grade,
		&i.GStatus,
		&i.PostedDate,
	)
	return i, err
}

const deleteGrade = `-- name: DeleteGrade :exec
DELETE FROM grades
WHERE id = $1
`

func (q *Queries) DeleteGrade(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGrade, id)
	return err
}

const getGrades = `-- name: GetGrades :many
SELECT
    g.id,
    g.grade,
    g.g_status,
    g.posted_date,
    c.course_name,
    c.course_id,
    c.professor_name
FROM grades g
JOIN courses c ON g.id_course = c.id
WHERE $1 = '' 
   OR c.course_name ILIKE '%' || $1 || '%' 
   OR c.course_id ILIKE '%' || $1 || '%'
   OR c.professor_name ILIKE '%' || $1 || '%'
ORDER BY
    -- Sort by date
    CASE WHEN $2 = 'date' AND $3 = 'asc' THEN g.posted_date END ASC,
    CASE WHEN $2 = 'date' AND $3 = 'desc' THEN g.posted_date END DESC,
    -- Sort by grade value
    CASE WHEN $2 = 'grade' AND $3 = 'asc' THEN g.grade END ASC,
    CASE WHEN $2 = 'grade' AND $3 = 'desc' THEN g.grade END DESC,
    -- Sort by course name
    CASE WHEN $2 = 'course' AND $3 = 'asc' THEN LOWER(c.course_name) END ASC,
    CASE WHEN $2 = 'course' AND $3 = 'desc' THEN LOWER(c.course_name) END DESC,
    -- Default fallback sorting
    g.posted_date DESC,
    g.id ASC
LIMIT $5
OFFSET $4
`

type GetGradesParams struct {
	Search     interface{}
	SortBy     interface{}
	SortDir    interface{}
	PageOffset int32
	NumRows    int32
}

type GetGradesRow struct {
	ID            pgtype.UUID
	Grade         int32
	GStatus       GradeStatus
	PostedDate    pgtype.Timestamptz
	CourseName    string
	CourseID      string
	ProfessorName string
}

func (q *Queries) GetGrades(ctx context.Context, arg GetGradesParams) ([]GetGradesRow, error) {
	rows, err := q.db.Query(ctx, getGrades,
		arg.Search,
		arg.SortBy,
		arg.SortDir,
		arg.PageOffset,
		arg.NumRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGradesRow
	for rows.Next() {
		var i GetGradesRow
		if err := rows.Scan(
			&i.ID,
			&i.Grade,
			&i.GStatus,
			&i.PostedDate,
			&i.CourseName,
			&i.CourseID,
			&i.ProfessorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGrade = `-- name: UpdateGrade :one
UPDATE grades
SET
    grade = COALESCE($1, grade),
    g_status = COALESCE($2, g_status),
    posted_date = COALESCE($3, posted_date)
WHERE id = $4
RETURNING id, id_course, grade, g_status, posted_date
`

type UpdateGradeParams struct {
	Grade      pgtype.Int4
	GStatus    NullGradeStatus
	PostedDate pgtype.Timestamptz
	ID         pgtype.UUID
}

func (q *Queries) UpdateGrade(ctx context.Context, arg UpdateGradeParams) (Grade, error) {
	row := q.db.QueryRow(ctx, updateGrade,
		arg.Grade,
		arg.GStatus,
		arg.PostedDate,
		arg.ID,
	)
	var i Grade
	err := row.Scan(
		&i.ID,
		&i.IDCourse,
		&i.Grade,
		&i.GStatus,
		&i.PostedDate,
	)
	return i, err
}
